### ISSUE TITLE
Running Tests

### ISSUE THREAD

**Issue by d4tocchini** [noflo/noflo-jekyll#1] opened 2013-01-02 08:21 UTC
when executing the tests via:

```
$ nodeunit test
```

i'm getting the following errors for Jekyll.coffee:

```
Jekyll
{ [Error: ENOTEMPTY, rmdir '/git/the-grid/noflo-jekyll/test/fixtures/noflo']
  errno: 53,
  code: 'ENOTEMPTY',
  path: '/git/the-grid/noflo-jekyll/test/fixtures/noflo' }
✖ test that NoFlo generates same files as Jekyll

AssertionError: NoFlo didn't generate file /bar.html
    at Object.assertWrapper [as fail] (/usr/local/lib/node/nodeunit/lib/types.js:83:39)
    at checkFile (/git/the-grid/noflo-jekyll/test/Jekyll.coffee:60:12)
    at checkDirectory (/git/the-grid/noflo-jekyll/test/Jekyll.coffee:98:21)
    at Object.exports.test that NoFlo generates same files as Jekyll (/git/the-grid/noflo-jekyll/test/Jekyll.coffee:104:5)
    at wrapTest (/usr/local/lib/node/nodeunit/lib/core.js:231:20)
    at _asyncMap (/usr/local/lib/node/nodeunit/deps/async.js:163:13)
    at async.forEachSeries.iterate (/usr/local/lib/node/nodeunit/deps/async.js:126:25)
    at _asyncMap (/usr/local/lib/node/nodeunit/deps/async.js:160:17)
    at async.series.results (/usr/local/lib/node/nodeunit/deps/async.js:458:34)
    at Network.exports.setUp (/git/the-grid/noflo-jekyll/test/Jekyll.coffee:43:16)

AssertionError: NoFlo didn't generate file /index.html
    at Object.assertWrapper [as fail] (/usr/local/lib/node/nodeunit/lib/types.js:83:39)
    at checkFile (/git/the-grid/noflo-jekyll/test/Jekyll.coffee:60:12)
    at checkDirectory (/git/the-grid/noflo-jekyll/test/Jekyll.coffee:98:21)
    at Object.exports.test that NoFlo generates same files as Jekyll (/git/the-grid/noflo-jekyll/test/Jekyll.coffee:104:5)
    at wrapTest (/usr/local/lib/node/nodeunit/lib/core.js:231:20)
    at _asyncMap (/usr/local/lib/node/nodeunit/deps/async.js:163:13)
    at async.forEachSeries.iterate (/usr/local/lib/node/nodeunit/deps/async.js:126:25)
    at _asyncMap (/usr/local/lib/node/nodeunit/deps/async.js:160:17)
    at async.series.results (/usr/local/lib/node/nodeunit/deps/async.js:458:34)
    at Network.exports.setUp (/git/the-grid/noflo-jekyll/test/Jekyll.coffee:43:16)

✔ test that NoFlo generates only the files Jekyll does

FAILURES: 2/2036 assertions failed (3415ms)
```

is this something you're working on, or am i running tests the wrong way?  it's my first time with nodeunit... i've been using [mocha](http://visionmedia.github.com/mocha/), but have been frustrated with it

are you using the default reporter?  gotta those love colored reports!

**Comment by bergie** [comment] 2013-01-02 10:11
@d4tocchini I don't think the issue is with nodeunit itself, but with some of the modules we use. Can you give me your Node.js version and the results of `npm list`?

This stuff will be easier to handle when we have CI...

**Comment by bergie** [comment] 2013-01-02 14:59
I tried this today on both Linux with Node 0.6.15, and on OS X with Node 0.8.16, and the tests passed on both without issues.

**Comment by d4tocchini** [comment] 2013-01-02 21:59
```
$ node -v 
v0.8.2
```

```
$ npm list
npm list
noflo-jekyll@0.0.1/git/the-grid/noflo-jekyll
├── coffee-script@1.4.0
├─┬ coffeelint@0.5.4
│ ├── coffee-script@1.4.0
│ ├─┬ glob@3.1.14
│ │ ├── graceful-fs@1.1.14
│ │ ├── inherits@1.0.0
│ │ └─┬ minimatch@0.2.9
│ │   ├── lru-cache@2.0.4
│ │   └── sigmund@1.0.0
│ ├─┬ optimist@0.3.5
│ │ └── wordwrap@0.0.2
│ └─┬ vows@0.6.4
│   ├── diff@1.0.4
│   └── eyes@0.1.8
├─┬ mimetype@0.0.4
│ └── harness@0.0.6
├─┬ nodeunit@0.7.4
│ └─┬ tap@0.3.3
│   ├── buffer-equal@0.0.0
│   ├── deep-equal@0.0.0
│   ├─┬ difflet@0.2.3
│   │ ├── charm@0.0.8
│   │ └── traverse@0.6.3
│   ├── inherits@1.0.0
│   ├── mkdirp@0.3.4
│   ├─┬ nopt@2.0.0
│   │ └── abbrev@1.0.3
│   ├─┬ runforcover@0.0.2
│   │ └─┬ bunker@0.1.2
│   │   └─┬ burrito@0.2.12
│   │     ├── traverse@0.5.2
│   │     └── uglify-js@1.1.1
│   ├── slide@1.1.3
│   └── yamlish@0.0.5
├─┬ noflo@0.3.0
│ ├─┬ cli@0.4.4-2
│ │ └─┬ glob@3.1.14
│ │   ├── graceful-fs@1.1.14
│ │   ├── inherits@1.0.0
│ │   └─┬ minimatch@0.2.9
│ │     ├── lru-cache@2.0.4
│ │     └── sigmund@1.0.0
│ ├─┬ cli-color@0.2.1
│ │ ├── es5-ext@0.9.1
│ │ └─┬ memoizee@0.2.3
│ │   ├── event-emitter@0.2.1
│ │   └── next-tick@0.1.0
│ ├─┬ npmlog@0.0.2
│ │ └── ansi@0.1.2
│ ├─┬ read-installed@0.0.4
│ │ ├── graceful-fs@1.1.14
│ │ ├─┬ read-package-json@0.1.12
│ │ │ ├─┬ glob@3.1.14
│ │ │ │ ├── inherits@1.0.0
│ │ │ │ └─┬ minimatch@0.2.9
│ │ │ │   └── sigmund@1.0.0
│ │ │ └── lru-cache@2.0.4
│ │ ├── semver@1.1.1
│ │ └── slide@1.1.3
│ ├─┬ shell@0.2.10
│ │ ├─┬ each@0.3.3
│ │ │ └─┬ glob@3.1.14
│ │ │   ├── graceful-fs@1.1.14
│ │ │   ├── inherits@1.0.0
│ │ │   └─┬ minimatch@0.2.9
│ │ │     ├── lru-cache@2.0.4
│ │ │     └── sigmund@1.0.0
│ │ ├─┬ optimist@0.3.5
│ │ │ └── wordwrap@0.0.2
│ │ └── pad@0.0.4
│ └── underscore@1.4.3
├─┬ noflo-liquid@0.0.5
│ └─┬ liquid-node@0.0.2
│   ├── coffee-script@1.4.0
│   └── underscore@1.4.3
├─┬ noflo-markdown@0.0.2
│ └── marked@0.2.6
├─┬ noflo-yaml@0.0.3
│ ├── js-yaml@0.3.7
│ └─┬ json2yaml@1.0.1
│   └── remedial@1.0.7
└─┬ rimraf@2.1.1
  └── graceful-fs@1.1.14
```

**Comment by bergie** [comment] 2013-08-08 14:27
This is fixed now.

**Closed as completed by bergie** 2013-08-08 14:27 UTC
Labels: question
